### ISSUE TITLE
Versions of tensorflow, cuda and cudnn

### ISSUE THREAD

**Issue by mquillot** [Goldesel23/Siamese-Networks-for-One-Shot-Learning#12]
Hello,
I'm trying to run your training script, but cudnn does not initalize. It is due to some conflicts with my tensorflow version apparently. Can you precise me the version you used to run your scripts, please?

Herlderlord

**Comment by tensorfreitas** [comment]
Hi @Herlderlord 

This is probably not related with the code. Can you run other TensorFlow examples? Or do you have cudnn problems only with this repo? 

When you install a specific version of TF you should install the correct cudnn version as described by the TF documentation

**Comment by mquillot** [comment]
I can run other tensorflow scripts on my gpu without any problem. I'm surprised that this does not work well. Maybe it is related to tensorboard.

**Comment by tensorfreitas** [comment]
This code might be incompatible with most recent versions of TensorFlow since it was written 2+ years ago. With all the changes from TensorFlow 2.0 you might need to adapt some code.

**Comment by mquillot** [comment]
Ok, I solved the problem. I'm working with tensorflow 1.14 and keras was not in the right version (2.2.5). Thank you for your help. :)
