### ISSUE TITLE
Version of tensorflow

### ISSUE THREAD

**Issue by JacksonLaw577** [Goldesel23/Siamese-Networks-for-One-Shot-Learning#13]
Hello，
Can you tell me which version of tensorflow you used in this code?
Thanks for this code!

**Comment by tensorfreitas** [comment]
Hi @JacksonLaw577 Sorry, I must have missed this message. I am pretty sure it was on tensorflow 1.** before tensorflow 2 being officially released. 

Sorry for the late response
