### ISSUE TITLE
How do I test the trained model?

### ISSUE THREAD

**Issue by LiaoPerry** [Goldesel23/Siamese-Networks-for-One-Shot-Learning#15]

**Comment by tensorfreitas** [comment]
Hi, 

After finishing the training the code already runs the test set. If you want to test it in a different dataset you would have to adapt the loader and the code for your application.

Best Regards
Tiago Freitas

**Comment by LiaoPerry** [comment]
Thank you very much for your reply!
I will try again

**Comment by tensorfreitas** [comment]
Feel free to reopen the issue if you find problems!
