### ISSUE TITLE
Dataset has same character in different labels (in one language)

### ISSUE THREAD

**Issue by Tastror** [Goldesel23/Siamese-Networks-for-One-Shot-Learning#22]
the character 07 08 09 in `Omniglot Dataset/images_background/Ojibwe_(Canadian_Aboriginal_Syllabics)` are same character (which means `n` in Ojibwe)

### character07
![image](https://user-images.githubusercontent.com/74226084/227330070-5d69732b-c9bc-41b9-93b4-96d8657cbc88.png)
### character08
![image](https://user-images.githubusercontent.com/74226084/227330133-c1c05659-f891-4dc5-9415-51dcb1c23f69.png)
### character09
![image](https://user-images.githubusercontent.com/74226084/227330195-d5e8e53d-fe59-47ce-8b73-d30069b43222.png)

**Comment by tensorfreitas** [comment]
Hi, the Omniglot dataset was directly taken from its original repository: 

https://github.com/brendenlake/omniglot

You can also see it here that is also present in the Original: 
https://knowyourdata-tfds.withgoogle.com/#dataset=omniglot&tab=RELATIONS&relations=default_segment.omniglot.alphabet.value,default_segment.omniglot.label.value&relations_selected=,Ojibwe_(Canadian_Aboriginal_Syllabics)_6&group_by=default_segment.omniglot.alphabet.value&select=default_segment.omniglot.label.value,default_segment.omniglot.alphabet.value&sort_asc=true

I am not sure if it is an error on the dataset or these letters are just too similar in this alphabet. Thanks for spotting it

**Comment by Tastror** [comment]
Thanks for the source, I'll check for the original dataset.
