### ISSUE TITLE
Author's implementation

### ISSUE THREAD

**Issue by pompha-dev** [Goldesel23/Siamese-Networks-for-One-Shot-Learning#6]
Hello, 
Can you please let me know where can I find author's implementation? You did mention that it slightly different. And what was the accuracy rate of your implementation? Thanks

**Comment by tensorfreitas** [comment]
Hi!

The authors did not share their implementation, I was referring to the details included in the paper. 

The accuracy was  > 82 % with some hyper parameter tuning.

If you have any more questions, feel free to reopen the issue!
