### ISSUE TITLE
prediction code

### ISSUE THREAD

**Issue by MansourTrabelsi** [Goldesel23/Siamese-Networks-for-One-Shot-Learning#7]
Hi,
I am a beginner in this field and I am really curious about one shot learning because I am facing the lack of data problem. So can you tell me how to use the resulted model to do the prediction.

Thank you

**Comment by tensorfreitas** [comment]
Hi, 

To use the model you will just need to frame the prediction as a one-shot task: Assume that you have 5 classes: give the model 5 pairs of images (one to be predicted and the reference class images). The pair with the highest score will be the predicted class. 

Hope this is enough to understand the prediction part.

Feel free to reopen if needed.
