### ISSUE TITLE
tensorboard_log_path and model weights

### ISSUE THREAD

**Issue by zjuzwb** [Goldesel23/Siamese-Networks-for-One-Shot-Learning#9]
Hi,
I tried to trian the network, but i can't find the tensorboard_log_path and the model weights? 
Could you please share these.

**Comment by tensorfreitas** [comment]
Hi @zjuzwb those two variables are for you to decide where to store the logs of tensorboard and the weights of the model being trained. By running the code it will store those logs and weights at those paths, respectively.
